pipeline {
    agent {
        label 'Slave'
    }
    stages {
        stage('Check config'){
            steps {
                sh 'java -version'
                echo "Get working directory"
                sh 'pwd'
            }
        }
    }
}